<?php

namespace Event\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * pariRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pariRepository extends EntityRepository
{
}
