<?php

namespace Event\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * jeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventRepository extends EntityRepository
{

}